### PR TITLE
US79

### PR DESCRIPTION
**Pull request by gschober**
Right-Click Email Option In Contacts Tab

### CODE REVIEW

**Comment by gschober** [comment]
Needs JUNIT Testing

**Comment by jrodri93** [comment]
CodeReview
- For JUnit testing on the contacts menu you could have initialize the contactsMenu on setup() to avoid initializing if for every test.
- I noticed on the contacts class that the contactsMenu was initialized twice, once on line 36 and again on line 111 along with adding it to the JPanel. If I'm not mistaken its not used there but on the contactsMenu.
- When selecting the first person in the contact panel to send an email to it returns an IllegalArgumentException.

**Comment by drmorri8** [comment]
Code Review:
- Previous recommendations are fixed: JUnit uses setup(), contactsMenu is initialized once, and no illegal argument exception on sending email to first contact.

**Comment by drmorri8** [comment]
Branch must be merged manually, created merge-branch.

**Pull request closed without merging**
